# Generated by Django 4.1.3 on 2023-12-28 19:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 28), verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен подтверждения'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_email_token', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Наименование'),
        ),
    ]
