# Generated by Django 4.1.3 on 2023-12-28 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_order_delivery_date_alter_confirmemailtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 31), verbose_name='Дата доставки'),
        ),
    ]
