# Generated by Django 4.1.3 on 2023-12-28 23:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 30), null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 12, 30))], verbose_name='Дата доставки'),
        ),
    ]
