# Generated by Django 4.1.3 on 2023-12-29 21:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 31), null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 12, 31))], verbose_name='Дата доставки'),
        ),
    ]
