# Generated by Django 4.1.3 on 2024-01-10 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_contact_options_alter_contact_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес пользователя', 'verbose_name_plural': 'Адреса пользователей'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('contact', 'region', 'district', 'settlement', 'street', 'house', 'structure', 'building', 'apartment')},
        ),
    ]
