# Generated by Django 4.1.3 on 2024-01-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_order_delivery_date_ratingproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingproduct',
            unique_together={('product', 'user')},
        ),
        migrations.AddField(
            model_name='ratingproduct',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв о товаре'),
        ),
    ]
