# Generated by Django 4.1.3 on 2024-01-31 03:27

import backend.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_user_avatar_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=backend.models.upload_ava_thumbnail_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.upload_ava_thumbnail_location, verbose_name='Аватар'),
        ),
    ]
