# Generated by Django 4.1.3 on 2024-01-31 11:59

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_user_avatar_alter_user_avatar_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfophoto',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='productinfophoto',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная иконка'),
        ),
        migrations.AlterField(
            model_name='productinfophoto',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
