# Generated by Django 4.1.3 on 2024-02-03 21:57

import backend.utils.media
import datetime
import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_productinfophoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 5), null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2024, 2, 5))], verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='productinfophoto',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=backend.utils.media.upload_icon_location, verbose_name='Изображение'),
        ),
    ]
